version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "$APPLICATION_NAME"
          ContainerPort: "$APPLICATION_PORT"
        PlatformVersion: "LATEST"