version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_ACCOUNT_ID - $AWS_DEFAULT_REGION - $APPLICATION_NAME
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME
      - export IMAGE_TAG_LATEST=$REPOSITORY_URI:latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $APPLICATION_NAME .
      - docker tag $APPLICATION_NAME $IMAGE_TAG_LATEST
      - echo Pushing the Docker image...
      - docker push $IMAGE_TAG_LATEST
  post_build:
    commands:
      - printf $(echo [{\"name\":\"$APPLICATION_NAME\",\"imageUri\":\"$IMAGE_TAG_LATEST\"}]) > imagedefinitions.json
      - printf $(echo {\"ImageURI\":\"$IMAGE_TAG_LATEST\"}) > imageDetail.json
      - envsubst < infrastructure/appspec_template.yml > appspec.yml 
      - envsubst < infrastructure/taskdef.temp.json > taskdef.json
artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - taskdef.json
