version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_ACCOUNT_ID - $AWS_DEFAULT_REGION - $APPLICATION_NAME
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $APPLICATION_NAME .
      - docker tag $APPLICATION_NAME $REPOSITORY_URI:latest
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - printf '[{"name":"container_name","imageUri":"$REPOSITORY_URI:latest"}]' > imagedefinitions.json
      - envsubst < infrastructure/appspec_template.yml > appspec.yml 
      - envsubst < infrastructure/taskdef.temp.json > taskdef.json
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
